### ISSUE TITLE
Request for Grade - Rationale

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/saas-website#1]
Hey @hellachella 

For this assignment, I think I deserve at least an A because I applied many, if not all, of the material we learned over this semester.  In my website, I used grids and grids in grids to make my website flow and look how I wanted and played with many classes from the typografier to get good, responsive type. I used classes from the modulifier to create responsive buttons, icons with labels, nice lists, and forms with different types of inputs (email, password, select, and radio). I made objects hide or show depending on the screen size and I created tables with multiple rows that are scrollable. I also made sure that my entire website was accessible with the proper focus sates depending on the background.

During this assignment I did have some struggles, particularly with making my navigation on small screens a toggle navigation. I had issues because, for the sake accessibility, a toggle navigation has difficulty with focus states making it not very accessible. I tried to make it work but ultimately changed my navigation to a standard navigation so that it would be accessible for all users.

Overall, I am very happy with how my website has turned out and I think it shows that I can apply everything I’ve learned in Wed Dev 2.

Thanks for the great semester!

Jess

**Comment by hellachella** [comment]
Bahaha, Shrute bucks.
